### ISSUE TITLE
你好，请问你light7的安卓弹出输入框怎么解决的

### ISSUE THREAD

**Issue by mushoujin** [ArleyJoe/ArleyJoe.github.io#1]
您好，我是初学者，能否把你用隐藏INPUT方法的JS让我看下，感激不尽，谢谢，在线等

**Comment by ArleyJoe** [comment]
首先非常抱歉，我最近一直忙，没有上来看。我解决的办法很简单，都是还是按照他文档中的调用方法来做的，只是把input的type设为了hidden，在input的上面覆盖了一层div（div的html内容取自input。）来作为了显示层。如果有什么可以给我发邮件来共同交流。
